id: 56
name: fbEmailGetJSON
description: 'DEPRECATED. Form data is now directly taken from CB properties field in fbValidateProcessJSON.'
category: f_formblocks
snippet: "/**\n * fbEmailGetJSON\n *\n * DEPRECATED. Form data is now directly taken from CB properties field in fbValidateProcessJSON.\n *\n * A snippet for FormBlocks that grabs the raw JSON data from the Properties column of the site_content table.\n * This data is being generated by ContentBlocks, and is used on the website to display the actual form.\n *\n * The result is being fed to the SIMPLX Widgeteer snippet.\n * This snippet is used to automatically generate the email template, based on the CB JSON data. It will template the JSON into rows for each field.\n * By using the complete output (and not f.i. cbGetFieldContent), the order of the fields is always correct in the email.\n *\n * @author Hugo Peek\n */\n\n$resourceID = $modx->getOption('formID', $scriptProperties, '');\n$resource = $modx->getObject('modResource', $resourceID);\n\n$rawData = $resource->getProperty('linear', 'contentblocks');\n$json = json_encode($rawData);\n\nreturn $json;"
properties: 'a:0:{}'
content: "/**\n * fbEmailGetJSON\n *\n * DEPRECATED. Form data is now directly taken from CB properties field in fbValidateProcessJSON.\n *\n * A snippet for FormBlocks that grabs the raw JSON data from the Properties column of the site_content table.\n * This data is being generated by ContentBlocks, and is used on the website to display the actual form.\n *\n * The result is being fed to the SIMPLX Widgeteer snippet.\n * This snippet is used to automatically generate the email template, based on the CB JSON data. It will template the JSON into rows for each field.\n * By using the complete output (and not f.i. cbGetFieldContent), the order of the fields is always correct in the email.\n *\n * @author Hugo Peek\n */\n\n$resourceID = $modx->getOption('formID', $scriptProperties, '');\n$resource = $modx->getObject('modResource', $resourceID);\n\n$rawData = $resource->getProperty('linear', 'contentblocks');\n$json = json_encode($rawData);\n\nreturn $json;"

-----


/**
 * fbEmailGetJSON
 *
 * DEPRECATED. Form data is now directly taken from CB properties field in fbValidateProcessJSON.
 *
 * A snippet for FormBlocks that grabs the raw JSON data from the Properties column of the site_content table.
 * This data is being generated by ContentBlocks, and is used on the website to display the actual form.
 *
 * The result is being fed to the SIMPLX Widgeteer snippet.
 * This snippet is used to automatically generate the email template, based on the CB JSON data. It will template the JSON into rows for each field.
 * By using the complete output (and not f.i. cbGetFieldContent), the order of the fields is always correct in the email.
 *
 * @author Hugo Peek
 */

$resourceID = $modx->getOption('formID', $scriptProperties, '');
$resource = $modx->getObject('modResource', $resourceID);

$rawData = $resource->getProperty('linear', 'contentblocks');
$json = json_encode($rawData);

return $json;