id: 433
name: configSettingsRow
description: 'Display a group of settings, as defined in the Configurations extra.'
category: m_hub
properties: 'a:2:{s:13:"elementStatus";a:7:{s:4:"name";s:13:"elementStatus";s:4:"desc";s:41:"romanesco.configsettingsrow.elementStatus";s:4:"type";s:9:"textfield";s:7:"options";s:0:"";s:5:"value";s:5:"solid";s:7:"lexicon";s:20:"romanesco:properties";s:4:"area";s:0:"";}s:14:"elementPreview";a:7:{s:4:"name";s:14:"elementPreview";s:4:"desc";s:42:"romanesco.configsettingsrow.elementPreview";s:4:"type";s:9:"textfield";s:7:"options";s:0:"";s:5:"value";s:0:"";s:7:"lexicon";s:20:"romanesco:properties";s:4:"area";s:0:"";}}'

-----

<h3 id="[[+label]]" class="ui header">
    [[+label]]
</h3>

<table class="ui very compact celled table">
    <thead>
    <tr>
        <th class="four wide">Key</th>
        <th class="five wide">Label</th>
        <th class="seven wide">Description</th>
    </tr>
    </thead>
    <tbody>
    [[migxLoopCollection?
        &packageName=`clientconfig`
        &classname=`cgSetting`
        &where=`{"group":"[[+id]]"}`
        &tpl=`configSettingsRowTR`
    ]]
    </tbody>
</table>