id: 578
name: overviewSettingsPrepare
description: 'A couple of placeholders need to be set, before the settings are evaluated in the snippet call.'
category: m_ov_settings
properties: 'a:2:{s:13:"elementStatus";a:7:{s:4:"name";s:13:"elementStatus";s:4:"desc";s:0:"";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:5:"solid";s:7:"lexicon";s:20:"romanesco:properties";s:4:"area";s:0:"";}s:14:"elementPreview";a:7:{s:4:"name";s:14:"elementPreview";s:4:"desc";s:0:"";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:0:"";s:7:"lexicon";s:20:"romanesco:properties";s:4:"area";s:0:"";}}'

-----

[[Switch:toPlaceholder=`[[+prefix]].sortdir`?
    &get=`[[+sortby]]_[[+sortdir]]`
    &c1=`menuindex_0`     &do1=`ASC`
    &c2=`publishedon_0`   &do2=`DESC`
    &c3=`createdon_0`     &do3=`DESC`
    &c4=`pagetitle_0`     &do4=`ASC`

    &c5=`menuindex_1`     &do5=`DESC`
    &c6=`publishedon_1`   &do6=`ASC`
    &c7=`createdon_1`     &do7=`ASC`
    &c8=`pagetitle_1`     &do8=`DESC`

    &default=`DESC`
]]
[[[[modifiedIf?
    &subject=`[[+img_type]]`
    &operator=`is`
    &operand=`svg`
    &then=`imgOverviewSVGLink`
    &else=`imgOverviewBasicLink`
    &toPlaceholder=`[[+prefix]].img_tpl`
]]]]
[[Switch:toPlaceholder=`[[+prefix]].icon_classes`?
    &get=`[[+icon_type]]`
    &c1=`svg`   &do1=`ui svg image`
    &c2=`font`  &do2=`ui icon image`
    &c3=`img`   &do3=`ui image`
]]
[[[[modifiedIf?
    &subject=`[[+prefix]]`
    &operator=`contains`
    &operand=`__`
    &then=`$overviewSettingsPrepareMgr`
]]]]